name: ❓ Question
description: Ask a Question about this library
title: "❓ "
labels: [❓ question]
body:
  - type: textarea
    attributes:
      label: Question
      description: Ask a question about the library or ask for help/advice. Make sure to be as detailed as possible, since well written questions are more likely to be picked up than badly written ones.
      placeholder: How do I take a photo?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What I tried
      description: (Optional) Explain what alternatives/workarounds you tried.
      placeholder: I tried to use `Camera.takePhoto()`
  - type: input
    attributes:
      label: Library Version
      description: Which version of react-native-snapchat-camera-kit are you using?
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Additional information
      description: Please check all the boxes that apply
      options:
        - label: I searched for [similar issues in this repository](https://github.com/popile-media/react-native-snapchat-camera-kit/issues) and found none.
          required: true