name: Build Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-docs.yml'
      - 'documentation/**'
      - 'src/**'
      - '*.json'
      - '*.js'
      - '*.lock'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-docs.yml'
      - 'documentation/**'
      - 'src/**'
      - '*.json'
      - '*.js'
      - '*.lock'

jobs:
  checks:
    if: github.event_name == 'pull_request'
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Test Docs Build
        run: |
          yarn install --frozen-lockfile
          cd documentation
          yarn install --frozen-lockfile
          yarn build
  gh-release:
    if: github.event_name == 'push'
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          cd documentation
          yarn install --frozen-lockfile

      - name: Build website
        run: |
          cd documentation
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
