name: Validate iOS

on:
  workflow_call:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - '.github/workflows/validate-ios.yml'
  #     - 'ios/**'
  pull_request:
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'ios/**'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run SwiftLint GitHub Action (--strict)
        uses: norio-nomura/action-swiftlint@master
        # with:
        # args: --strict
        env:
          WORKING_DIRECTORY: ios
  SwiftFormat:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./ios
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Format Swift code
        run: swiftformat --verbose .

      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD
